name: CI
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      # Note: the following folder layout matters:
      # parent_dir:
      #   - spilo-build
      #   - Hydras
      #   - citus
      #   - spilo
      - name: Checkout spilo-build
        uses: actions/checkout@v2
        with:
          path: spilo-build
      - name: Checkout Hydras
        uses: actions/checkout@v2
        with:
          repository: HydrasCo/Hydras
          token: ${{ secrets.GH_TOKEN }}
          path: Hydras
      - name: Checkout citus
        uses: actions/checkout@v2
        with:
          repository: HydrasCo/citus
          token: ${{ secrets.GH_TOKEN }}
          path: citus
      - name: Checkout spilo
        uses: actions/checkout@v2
        with:
          repository: HydrasCo/spilo
          token: ${{ secrets.GH_TOKEN }}
          path: spilo
      - name: Run build
        working-directory: ./spilo-build
        run: |
          (cd ./Hydras && HYDRAS_SHA=$(git rev-parse --short HEAD))
          (cd ./citus && COLUMNAR_SHA=$(git rev-parse --short HEAD))
          (cd ./spilo && SPILO_SHA=$(git rev-parse --short HEAD))

          TAG=${SPILO_SHA}-${COLUMNAR_SHA}-${HYDRAS_SHA} SPILO_REPO=011789831835.dkr.ecr.us-east-1.amazonaws.com/spilo make
